language: cpp

compiler:
  - clang
  - gcc

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - autoconf
      - autoconf-archive
      - automake

branches:
  only:
    - afe-maintenance

install: true

before_script:
    - autoreconf --install

script:
    - ./configure && make -j8 && make check
